Repository openshift/contra-lib, pull requests merged in 2018-12, with the labels that each got.

#31 only return commit sha
  src/org/centos/contra/pipeline/GitHubAPI.groovy
Labels: size/XS

#32 return merged sha
  src/org/centos/contra/pipeline/GitHubAPI.groovy
Labels: size/XS

#33 Add functions for updated message spec
  README.md
  resources/msgBusArtifactContent.json
  resources/msgBusCIContent.json
  resources/msgBusContainerContent.json
  resources/msgBusHeader.json
  resources/msgBusPipelineContent.json
  resources/msgBusRunContent.json
  resources/msgBusStageContent.json
  resources/msgBusSystemContent.json
  resources/msgBusTestComplete.json
  resources/msgBusTestContent.json
  resources/msgBusTestError.json
  resources/msgBusTestQueued.json
  resources/msgBusTestRunning.json
  src/org/centos/contra/pipeline/Utils.groovy
  vars/fedMsgComplete.groovy
  vars/fedMsgError.groovy
  vars/fedMsgHeader.groovy
  vars/msgBusArtifactContent.groovy
  vars/msgBusCIContent.groovy
  vars/msgBusContainerContent.groovy
  vars/msgBusHeader.groovy
  vars/msgBusPipelineContent.groovy
  vars/msgBusRunContent.groovy
  vars/msgBusStageContent.groovy
  vars/msgBusSystemContent.groovy
  vars/msgBusTestComplete.groovy
  vars/msgBusTestContent.groovy
  vars/msgBusTestError.groovy
  vars/msgBusTestQueued.groovy
  vars/msgBusTestRunning.groovy
Labels: size/XXL

#34 Image push
  vars/buildTestContainer.groovy
Labels: size/S

#35 Add option to return stdout from executeInContainer
  vars/executeInContainer.groovy
Labels: size/XS

#36 Update artifact closure for PR fields
  resources/msgBusArtifactContent.json
  src/org/centos/contra/pipeline/Utils.groovy
Labels: size/M

#38 boolean needed
  src/org/centos/contra/jobdsl/PipelineJob.groovy
Labels: size/XS

#37 Add pipeline.* messages
  resources/msgBusPipelineContent.json
  resources/msgBusPipelineMsg.json
  resources/msgBusRunContent.json
  resources/msgBusStageContent.json
  resources/msgBusStageMsg.json
  vars/msgBusPipelineMsg.groovy
  vars/msgBusStageMsg.groovy
Labels: size/L
