Repository openshift/contra-lib, pull requests merged in 2018-09, with the labels that each got.

#16 More defaults
  README.md
  vars/ciPipeline.groovy
  vars/deployOpenShiftTemplate.groovy
Labels: size/M

#17 Documentation update
  README.md
Labels: size/S

#18 job dsl update
  src/org/centos/contra/jobdsl/MultiBranchJob.groovy
  src/org/centos/contra/pipeline/Utils.groovy
  src/org/centos/contra/pipeline/ciMetrics.groovy
  vars/ciPipeline.groovy
  vars/deployOpenShiftTemplate.groovy
  vars/handlePipelineStep.groovy
  vars/kojiMessage.groovy
  vars/pipelineMetrics.groovy
  vars/prBuild.groovy
  vars/prMessage.groovy
  vars/sendMessageWithAudit.groovy
  vars/setCustomMetric.groovy
  vars/stageTrigger.groovy
Labels: size/M

#19 added function to resize compose
  vars/resizeCompose.groovy
Labels: needs-ok-to-test, size/XS

#21 Add PipelineJob library
  src/org/centos/contra/jobdsl/MultiBranchJob.groovy
  src/org/centos/contra/jobdsl/PipelineJob.groovy
Labels: size/L
