Repository openshift/contra-lib, pull requests merged in 2018-10, with the labels that each got.

#23 Github api
  src/org/centos/contra/pipeline/GitUtils.groovy
  src/org/centos/contra/pipeline/Utils.groovy
Labels: size/M

#25 allow specify container name on resizeCompose
  vars/resizeCompose.groovy
  vars/testCompose.groovy
Labels: needs-ok-to-test, size/XS

#26 Change containers to containersWithProps in JenkinsfileExample
  JenkinsfileExample
Labels: size/XS

#27 Add image name container prop to deployOpenShiftTemplate
  vars/deployOpenShiftTemplate.groovy
Labels: size/XS

#28 Add build_number to pipelineMetrics
  vars/pipelineMetrics.groovy
Labels: size/XS
