Repository openshift/contra-lib, pull requests merged in 2019-03, with the labels that each got.

#65 do apply patch from PR, but merge changes from it
  src/org/centos/contra/pipeline/Utils.groovy
Labels: needs-ok-to-test, size/XS

#66 alternate namespace support
  vars/deployOpenShiftTemplate.groovy
Labels: size/XS

#67 Make system a list
  resources/msgBusTestComplete.json
Labels: size/XS

#68 Updates for spec changes
  resources/msgBusArtifactContent.json
  resources/msgBusCIContent.json
  resources/msgBusErrorContent.json
  resources/msgBusHeader.json
  resources/msgBusNotificationContent.json
  resources/msgBusPipelineContent.json
  resources/msgBusRunContent.json
  resources/msgBusStageContent.json
  resources/msgBusSystemContent.json
  resources/msgBusTestComplete.json
  resources/msgBusTestContent.json
  resources/msgBusTestError.json
  resources/msgBusTestQueued.json
  resources/msgBusTestRunning.json
  vars/msgBusErrorContent.groovy
  vars/msgBusNotificationContent.groovy
  vars/msgBusTestError.groovy
Labels: size/XL

#70 make required enforcing again
  src/org/centos/contra/pipeline/Utils.groovy
Labels: size/XS
