Repository openshift/contra-lib, pull requests merged in 2019-01, with the labels that each got.

#39 Add ci.pipeline.stage.[running,complete] messages
  resources/msgBusPipelineContent.json
  resources/msgBusPipelineMsg.json
  resources/msgBusStageContent.json
  resources/msgBusStageMsg.json
  src/org/centos/contra/pipeline/Utils.groovy
  vars/ciStage.groovy
  vars/msgBusArtifactContent.groovy
  vars/msgBusCIContent.groovy
  vars/msgBusContainerContent.groovy
  vars/msgBusHeader.groovy
  vars/msgBusPipelineContent.groovy
  vars/msgBusPipelineMsg.groovy
  vars/msgBusRunContent.groovy
  vars/msgBusStageContent.groovy
  vars/msgBusStageMsg.groovy
  vars/msgBusSystemContent.groovy
  vars/msgBusTestComplete.groovy
  vars/msgBusTestContent.groovy
  vars/msgBusTestError.groovy
  vars/msgBusTestQueued.groovy
  vars/msgBusTestRunning.groovy
  vars/sendMessageWithAudit.groovy
  vars/setEnvVars.groovy
Labels: size/L

#40 Update README for ciStage function
  README.md
Labels: size/S

#41 Add methods to identify details about OpenShift
  src/org/centos/contra/pipeline/Utils.groovy
Labels: size/M

#42 Check if the logs and props file even exist
  vars/executeInContainer.groovy
Labels: size/XS

#44 Update README for info about pipeline.status msgs in ciPipeline
  README.md
Labels: size/XS

#47 run commands from within stageName directory
  vars/executeInContainer.groovy
Labels: size/S

#48 removing dir and using absolute paths
  vars/executeInContainer.groovy
Labels: size/S

#50 Fix mkdir command in executeInContainer to skip if directory exists
  vars/executeInContainer.groovy
Labels: size/XS

#51 Make pipeline status msgs easier in declarative
  vars/ciPipeline.groovy
  vars/msgBusPipelineContent.groovy
  vars/sendPipelineStatusMsg.groovy
Labels: size/M

#52 Update README for sendPipelineStatusMsg
  README.md
Labels: size/M

#49 Inject all vars in kojiMessage
  src/org/centos/contra/pipeline/Utils.groovy
  vars/kojiMessage.groovy
Labels: size/M

#53 Spec change for some of the test keys
  resources/msgBusTestComplete.json
  resources/msgBusTestContent.json
  resources/msgBusTestError.json
  resources/msgBusTestQueued.json
  resources/msgBusTestRunning.json
  vars/msgBusTestComplete.groovy
  vars/msgBusTestError.groovy
  vars/msgBusTestQueued.groovy
  vars/msgBusTestRunning.groovy
Labels: size/L
