Repository openshift/contra-lib, pull requests merged in 2019-02, with the labels that each got.

#54 Output error message for failure
  vars/msgBusArtifactContent.groovy
  vars/msgBusCIContent.groovy
  vars/msgBusContainerContent.groovy
  vars/msgBusHeader.groovy
  vars/msgBusPipelineContent.groovy
  vars/msgBusPipelineMsg.groovy
  vars/msgBusRunContent.groovy
  vars/msgBusStageContent.groovy
  vars/msgBusStageMsg.groovy
  vars/msgBusSystemContent.groovy
  vars/msgBusTestComplete.groovy
  vars/msgBusTestContent.groovy
  vars/msgBusTestError.groovy
  vars/msgBusTestQueued.groovy
  vars/msgBusTestRunning.groovy
Labels: size/M

#55 Fix syntax error when creating thread_id by UUID generator
  vars/msgBusTestComplete.groovy
  vars/msgBusTestError.groovy
Labels: needs-ok-to-test, size/XS

#56 Document req scriptApprovals for msging
  README.md
Labels: size/S

#57 Make fields in build but not pr spec not req
  resources/msgBusArtifactContent.json
Labels: size/XS

#58 Change header json
  resources/msgBusHeader.json
Labels: size/M

#59 Few test array spec changes I missed
  resources/msgBusTestContent.json
  src/org/centos/contra/pipeline/Utils.groovy
  vars/msgBusTestComplete.groovy
  vars/msgBusTestContent.groovy
Labels: size/S

#60 Spec version should have been incremented
  resources/msgBusTestComplete.json
  resources/msgBusTestError.json
  resources/msgBusTestQueued.json
  resources/msgBusTestRunning.json
Labels: size/XS

#61 retry to install package during testCompose
  vars/testCompose.groovy
Labels: needs-ok-to-test, size/S

#62 fix typo on running python command
  vars/testCompose.groovy
Labels: needs-ok-to-test, size/XS

#63 Add some general utils fedora pipeline uses
  src/org/centos/contra/pipeline/Utils.groovy
Labels: size/L

#64 Remove thread_id, add topic to error statement
  resources/msgBusTestComplete.json
  resources/msgBusTestError.json
  resources/msgBusTestQueued.json
  resources/msgBusTestRunning.json
  src/org/centos/contra/pipeline/Utils.groovy
  vars/msgBusTestComplete.groovy
  vars/msgBusTestError.groovy
  vars/msgBusTestQueued.groovy
  vars/msgBusTestRunning.groovy
Labels: size/M
