Repository openshift/contra-lib, pull requests merged in 2019-09, with the labels that each got.

#83 Display labels instead of 'Shell Script' in the Blue Ocean
  src/org/centos/contra/pipeline/Utils.groovy
  vars/downloadCompose.groovy
Labels: size/S

#84 Don't use depth 1 in clone for checkTests with PR
  src/org/centos/contra/pipeline/Utils.groovy
Labels: size/XS

#86 add pullId param to buildOpenShiftImage
  vars/buildOpenShiftImage.groovy
Labels: size/S

#87 fix buildOpenShiftImage
  vars/buildOpenShiftImage.groovy
Labels: size/XS

#89 support change pagure url
  src/org/centos/contra/pipeline/Utils.groovy
Labels: size/XS

#90 Define topicSuffix earlier in ciPipeline
  vars/ciPipeline.groovy
Labels: size/XS

#88 Add product-build artifact to msg structure
  resources/msgBusArtifactContent.json
  vars/msgBusArtifactContent.groovy
Labels: size/S

#85 Remove duplicated function
  src/org/centos/contra/pipeline/Utils.groovy
Labels: size/M
